/* tslint:disable */
/* eslint-disable */
/**
 * The User API
 * API to manage teams, members and tokens
 *
 * The version of the OpenAPI document: 1.3.9 cumulative-hardin
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Token,
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
} from './';

/**
 * 
 * @export
 * @interface DeleteTokenResponse
 */
export interface DeleteTokenResponse {
    /**
     * 
     * @type {Token}
     * @memberof DeleteTokenResponse
     */
    token?: Token;
}

export function DeleteTokenResponseFromJSON(json: any): DeleteTokenResponse {
    return DeleteTokenResponseFromJSONTyped(json, false);
}

export function DeleteTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteTokenResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : TokenFromJSON(json['token']),
    };
}

export function DeleteTokenResponseToJSON(value?: DeleteTokenResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': TokenToJSON(value.token),
    };
}


