/* tslint:disable */
/* eslint-disable */
/**
 * The User API
 * API to manage teams, members and tokens
 *
 * The version of the OpenAPI document: 1.3.13 bordering-jerilyn
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserProfile,
    UserProfileFromJSON,
    UserProfileFromJSONTyped,
    UserProfileToJSON,
} from './';

/**
 * 
 * @export
 * @interface MemberOfATeam
 */
export interface MemberOfATeam {
    /**
     * 
     * @type {string}
     * @memberof MemberOfATeam
     */
    role?: string;
    /**
     * 
     * @type {UserProfile}
     * @memberof MemberOfATeam
     */
    user?: UserProfile;
}

export function MemberOfATeamFromJSON(json: any): MemberOfATeam {
    return MemberOfATeamFromJSONTyped(json, false);
}

export function MemberOfATeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberOfATeam {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'role': !exists(json, 'role') ? undefined : json['role'],
        'user': !exists(json, 'user') ? undefined : UserProfileFromJSON(json['user']),
    };
}

export function MemberOfATeamToJSON(value?: MemberOfATeam | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': value.role,
        'user': UserProfileToJSON(value.user),
    };
}


