/* tslint:disable */
/* eslint-disable */
/**
 * The User API
 * API to manage teams, members and tokens
 *
 * The version of the OpenAPI document: 1.3.13 bordering-jerilyn
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestInviteDetails
 */
export interface RequestInviteDetails {
    /**
     * The invite code.
     * @type {string}
     * @memberof RequestInviteDetails
     */
    code?: string;
}

export function RequestInviteDetailsFromJSON(json: any): RequestInviteDetails {
    return RequestInviteDetailsFromJSONTyped(json, false);
}

export function RequestInviteDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestInviteDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
    };
}

export function RequestInviteDetailsToJSON(value?: RequestInviteDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
    };
}


